(module (func (export "_start") (param $a i32) (param $b i32) (result i32)
    (local $sum i32)
        (local.set $sum (i32.add (local.get $a) (local.get $b)))
    (i32.div_s (local.get $sum) (i32.const 2))
))
